apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::562364260873:role/eksNodeRole
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: "- userarn: arn:aws:iam::562364260873:user/system/sre \n  # username:
    sre \n  groups:\n    - system:masters\n"
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
